#!/system/bin/sh
# call userinit.sh and/or userinit.d/* scripts if present in /data/local

if [ -e /data/local/userinit.sh ];
then
   log -p i -t userinit "Executing /data/local/userinit.sh";
   logwrapper /system/bin/sh /data/local/userinit.sh;
   setprop ada.userinit.active 1;
fi;

if [ -d /data/local/userinit.d ];
then
   logwrapper busybox run-parts /data/local/userinit.d;
   setprop ada.userinit.active 1;
fi;

# tweak block dev I/O
BLOCK_DEVS=`ls -d /sys/block/mmc*`;
BLOCK_DEVS="$BLOCK_DEVS `ls -d /sys/block/mtd*`";

for i in $BLOCK_DEVS;
do
    echo 0 > $i/queue/rotational; 
    echo 16 > $i/queue/iosched/fifo_batch;
    echo 256 > $i/queue/max_sectors_kb;
    echo 1024 > $i/queue/read_ahead_kb;
done;

# VM tweaks
echo 0 > /proc/sys/vm/laptop_mode
echo 0 > /proc/sys/vm/swappiness
echo 50 > /proc/sys/vm/vfs_cache_pressure
echo 90 > /proc/sys/vm/dirty_ratio
echo 40 > /proc/sys/vm/dirty_background_ratio
echo 2000 > /proc/sys/vm/dirty_writeback_centisecs
echo 1000 > /proc/sys/vm/dirty_expire_centisecs
